### PR TITLE
Remove `Default` implementations and add a `DefaultToHost` utility.

### LINKED ISSUE #49: Return host() for default(), not unknown
Currently, the `Default` implementation for Triple is not very useful. I'd rather have it return the host triple instead of `unknown-unknown-unknown-unknown`.

I'd make this a PR instead of an issue, except I'm having trouble with the change and I don't know why:
```
$ git diff
diff --git a/src/triple.rs b/src/triple.rs
index fe96159..fad0c43 100644
--- a/src/triple.rs
+++ b/src/triple.rs
@@ -131,13 +131,7 @@ impl Triple {
 
 impl Default for Triple {
     fn default() -> Self {
-        Self {
-            architecture: Architecture::Unknown,
-            vendor: Vendor::Unknown,
-            operating_system: OperatingSystem::Unknown,
-            environment: Environment::Unknown,
-            binary_format: BinaryFormat::Unknown,
-        }
+        Triple::host()
     }
 }
$ cargo check
error[E0599]: no function or associated item named `host` found for type `triple::Triple` in the current scope
   --> src/triple.rs:134:17
    |
76  | pub struct Triple {
    | ----------------- function or associated item `host` not found for this
...
134 |         Triple::host()
    |                 ^^^^ function or associated item not found in `triple::Triple`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `target-lexicon`
```

I know `Triple` has a `host` function, I'm not sure why it's not showing up here.
```

### PR DESCRIPTION
**Pull request by sunfishcode**
The `Default` implementations here were inspired by target triple
parsing, where the various fields default to "unknown", however they
doesn't make as much sense outside of that context. So, remove the
`Default` implementations, and add a separate `DefaultToHost` for
use by users that want a `Triple` that defaults to targeting the host.

Fixes #49.

### CODE REVIEW

File: src/default_to_host.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
...
+
+/// A simple wrapper around `Triple` that provides an implementation of
+/// `Default` which defaults to `Triple::host()`.
+pub struct DefaultToHost(pub Triple);
+
+impl Default for DefaultToHost {
+    fn default() -> Self {
+        Self(Triple::host())
+    }
+}
```
Comment (bjorn3) [inline src/default_to_host.rs]: Maybe move this to `lib.rs` as this is tiny?

Comment (sunfishcode) [reply src/default_to_host.rs]: Done
